# Generated by Django 4.1.3 on 2022-11-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('items', models.ManyToManyField(to='backend_bistro.menuitem')),
            ],
        ),
    ]
