# Generated by Django 4.1.3 on 2022-11-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantNameMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuItem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_bistro.menuitem')),
                ('restaurantname_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_bistro.restaurantname')),
            ],
        ),
    ]
