# Generated by Django 4.1.3 on 2022-11-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0002_restaurantname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantname',
            name='items',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='items',
            field=models.ManyToManyField(to='backend_bistro.restaurantname'),
        ),
    ]
