# Generated by Django 4.1.3 on 2022-11-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0005_alter_menuitem_category_id_alter_menuitem_cuisine_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='cuisine',
            old_name='types',
            new_name='title',
        ),
    ]
